### ISSUE TITLE
Quantify the download time and price from a bucket

### ISSUE THREAD

**Issue by katilp** [cms-dpoa/cloud-processing#19]
A typical quantity of the output data of a processing step is some tens to 100 GB.

See e.g. the sizes of these [derived data](https://opendata.cern.ch/search?q=&f=type%3ADataset%2Bsubtype%3ADerived&f=file_type%3Ananoaod-pf&l=list&order=desc&p=1&s=10&sort=mostrecent)

Quantify the time and price to download e.g, a 1 GB file.
Take into account the distance from your location and the google data center, i.e. evaluate for example
Finland (europe-north1), Netherlands (europe-west4), Zürich(europe-west6).

Later on, make sure that the estimate scale linearly with the size by checking with some larger files.

**Comment by katilp** [comment]
Some care is needed. This needs to be done with a high and constant download speed to make sure that we do not measure our own download speed. We want to know if it goes slow because of the GCS.

I had this impression but it is all to be verified.

@subash-taranga please plan the test so that it is easy to repeat, preferably a terraform script.

**Comment by subash-taranga** [comment]
@katilp sure we will do ......lets discuss this more in tomorrow meet as well

**Comment by subash-taranga** [comment]
@katilp ....As tested 7 world wide locations and 4 Europe locations below are some key points for bucket data download

01) Doesn't matter the location but download time is nearly same for all locations files starting from 200MB to 10GB.
(Assume we use single region bucket with Standard storage class whereas we don't use  Nearline, Coldline, Archive classes )
(Further we assume that end user local PC/Laptop is in average accepted performances)

02) Download time is totally depend on download speed. For me average download speed was 10 MiB/s as per log file (This speed determine by end user ISP connection . Please note 10 MiB/s×8.388608=83.88608 Mbps)

this 84 Mbps was my ISP Connection download speed

So for the bucket regardless the location,  download time determine by ISP connation download speed..............................

-----------------------------------------------------------------------------------------------------------------------------------

I need your help to enable BigQuery billing on my GCP ....I mean does it enable from your side

**Comment by katilp** [comment]
A good point on MiB/s vs Mbps, I did not notice that. Can you please add the logs here?

Do you have the possibility of trying in some other locations where the local download speed is different?

For the BigQuery billing, please create a data set and give it a name so that I can direct the billing data there.

**Comment by subash-taranga** [comment]
THIS IS  A ONE LOG FILE FOR THE GCP LOCATION FINLAND
====================================================
Copying gs://bucket-europe-north1-finland/200.txt...
- [1/1 files][200.0 MiB/200.0 MiB] 100% Done  11.4 MiB/s ETA 00:00:00
Operation completed over 1 objects/200.0 MiB.

real    0m20.219s
user    0m3.270s
sys     0m1.929s
Copying gs://bucket-europe-north1-finland/300.txt...
/ [1/1 files][300.0 MiB/300.0 MiB] 100% Done   9.7 MiB/s ETA 00:00:00
Operation completed over 1 objects/300.0 MiB.

real    0m32.020s
user    0m4.052s
sys     0m1.955s
Copying gs://bucket-europe-north1-finland/512.txt...
/ [1/1 files][512.0 MiB/512.0 MiB] 100% Done  10.0 MiB/s ETA 00:00:00
Operation completed over 1 objects/512.0 MiB.

real    0m49.162s
user    0m6.975s
sys     0m3.526s
Copying gs://bucket-europe-north1-finland/700.txt...
/ [1/1 files][700.0 MiB/700.0 MiB] 100% Done  10.4 MiB/s ETA 00:00:00
Operation completed over 1 objects/700.0 MiB.

real    1m7.144s
user    0m9.034s
sys     0m4.845s
Copying gs://bucket-europe-north1-finland/1GB.zip...
| [1/1 files][  1.0 GiB/  1.0 GiB] 100% Done   8.2 MiB/s ETA 00:00:00
Operation completed over 1 objects/1.0 GiB.

real    1m37.556s
user    0m12.135s
sys     0m6.858s
Copying gs://bucket-europe-north1-finland/1_5GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/1_5GB/512MB.zip.crdownload...
| [2/2 files][  1.5 GiB/  1.5 GiB] 100% Done  10.1 MiB/s ETA 00:00:00
Operation completed over 2 objects/1.5 GiB.

real    2m24.417s
user    0m20.653s
sys     0m11.281s
Copying gs://bucket-europe-north1-finland/2GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/2GB/1GB/1GB.zip...
- [2/2 files][  2.0 GiB/  2.0 GiB] 100% Done   9.1 MiB/s ETA 00:00:00
Operation completed over 2 objects/2.0 GiB.

real    3m13.086s
user    0m26.560s
sys     0m14.579s
Copying gs://bucket-europe-north1-finland/2_5GB/2GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/2_5GB/2GB/1GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/2_5GB/512MB.zip.crdownload...
/ [3/3 files][  2.5 GiB/  2.5 GiB] 100% Done   8.2 MiB/s ETA 00:00:00
Operation completed over 3 objects/2.5 GiB.

real    3m58.967s
user    0m32.697s
sys     0m16.578s
Copying gs://bucket-europe-north1-finland/5GB/1GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/5GB/2GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/5GB/2GB/1GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/5GB/2GB/2GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/5GB/2GB/2GB/1GB/1GB.zip...
/ [5/5 files][  5.0 GiB/  5.0 GiB] 100% Done  10.4 MiB/s ETA 00:00:00
Operation completed over 5 objects/5.0 GiB.

real    7m57.123s
user    1m12.072s
sys     0m33.424s
Copying gs://bucket-europe-north1-finland/7_5GB/2.5GB/2GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/7_5GB/2.5GB/2GB/1GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/7_5GB/2.5GB/512MB.zip.crdownload...
Copying gs://bucket-europe-north1-finland/7_5GB/5GB/1GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/7_5GB/5GB/2GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/7_5GB/5GB/2GB/1GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/7_5GB/5GB/2GB/2GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/7_5GB/5GB/2GB/2GB/1GB/1GB.zip...
/ [8/8 files][  7.5 GiB/  7.5 GiB] 100% Done   8.9 MiB/s ETA 00:00:00
Operation completed over 8 objects/7.5 GiB.

real    11m58.011s
user    1m53.184s
sys     0m48.541s
Copying gs://bucket-europe-north1-finland/10GB/5GB/1GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/10GB/5GB/2GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/10GB/5GB/2GB/1GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/10GB/5GB/2GB/2GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/10GB/5GB/2GB/2GB/1GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/10GB/5GB/5GB/1GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/10GB/5GB/5GB/2GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/10GB/5GB/5GB/2GB/1GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/10GB/5GB/5GB/2GB/2GB/1GB.zip...
Copying gs://bucket-europe-north1-finland/10GB/5GB/5GB/2GB/2GB/1GB/1GB.zip...
\ [10/10 files][ 10.0 GiB/ 10.0 GiB] 100% Done  10.0 MiB/s ETA 00:00:00
Operation completed over 10 objects/10.0 GiB.

real    15m55.075s
user    2m46.176s
sys     1m8.722s
subash@MSI:/mnt/c/SUBASH/G-CLOUD/BUCKET$

**Comment by subash-taranga** [comment]
> A good point on MiB/s vs Mbps, I did not notice that. Can you please add the logs here?
> 
> Do you have the possibility of trying in some other locations where the local download speed is different?
> Sure  i will try.........................good point to make sure the finding ...............
> For the BigQuery billing, please create a data set and give it a name so that I can direct the billing data there.
yes i will do

**Comment by subash-taranga** [comment]
@katilp ...............still i have doubt.  if we compare MiB/s Vs MBps i think there will not be a much differ
                                        whereas if we compare MiB/s Vs Mbps it will be 8 times as 1 Byte is equal to 8 bit.....what do you think.............

this shows the online conversion 
https://www.convertunits.com/from/MiB/s/to/Mbps

**Comment by katilp** [comment]
MiB is bytes, not bits.
