### ISSUE TITLE
BigQuery for billing data export

### ISSUE THREAD

**Issue by tomcordruw** [cms-dpoa/cloud-processing#20]
Using BigQuery to read the detailed cost and billing data for Google Cloud.

https://cloud.google.com/billing/docs/how-to/export-data-bigquery-setup

**Comment by tomcordruw** [comment]
@katilp 
I am setting up a BigQuery dataset for the billing data, but in order to export the data to it, I would need the Billing Account Administrator role (roles/billing.admin).
Seems like the easiest way to set it up is from the Account Management page under Billing:
https://console.cloud.google.com/billing/manage

**Comment by katilp** [comment]
It is very obscure, I've now added a Project Billing Manager role for you through IAM. 
It does not look to me that it changed anything. And I do not see billing.admin in the list of possible roles:


![Image](https://github.com/cms-dpoa/cloud-processing/assets/5859918/fd9fde86-8883-4951-b0e7-95faf581d6a7)


The billing/manage link does not give any other option than closing the billing account

**Comment by katilp** [comment]
Maybe it is OK:

![Image](https://github.com/cms-dpoa/cloud-processing/assets/5859918/66cd605a-06f2-4d46-bbad-69bf564ad2f0)

Let me know.

**Comment by tomcordruw** [comment]
Hm, strange. I need to access "Billing export" seen here in another project where I have the correct permissions:

![Image](https://github.com/cms-dpoa/cloud-processing/assets/93997143/1c46f4ed-a107-4c68-8e75-1e05d9bae18e)

Meanwhile the view in my GCS-bucket-Tom project is like this:

![Image](https://github.com/cms-dpoa/cloud-processing/assets/93997143/7ca92dab-f0ae-42a4-be45-c4de19cc6c0e)

**Comment by katilp** [comment]
OK, so that was not enough.
Can you show me the permissions for that other project?

**Comment by tomcordruw** [comment]
As I understand the documentation here:  https://cloud.google.com/billing/docs/how-to/grant-access-to-billing

The way to do it is to go to Billing -> Account Management
And then add principal in the info panel here:

![Image](https://github.com/cms-dpoa/cloud-processing/assets/93997143/8e06214d-8ca0-4aa7-b644-e6e7d4c731e4)

When clicking on `ADD PRINCIPAL` I can enter my email address and find the Billing Account Administrator-role.

![Image](https://github.com/cms-dpoa/cloud-processing/assets/93997143/b59937be-4301-4d7d-9281-461a3620641b)

**Comment by tomcordruw** [comment]
I see, these permissions are tied to what a user is allowed to do in relation to billing account, not the project.
So the Billing Account Administrator role is given to users to manage the billing account (called "My Billing Account" in my case), whereas IAM handles the roles and permissions to the project "GCS-bucket-Tom".

That's why I can't do much in the Billing tab, because I don't have permissions in regards to the billing account:

![Image](https://github.com/cms-dpoa/cloud-processing/assets/93997143/e38bb850-104e-410b-be5f-515b54960a1b)

**Comment by katilp** [comment]
But now as you have the `role/billing.admin` in your project (through IAM) can you use BigQuery in that project?

Or is the BigQuery setup independent from the projects?

**Comment by tomcordruw** [comment]
The BigQuery billing export seems to be working and I can see the costs and other information in a table that was added to the dataset.
Issue closed.

**Comment by subash-taranga** [comment]
![Image](https://github.com/user-attachments/assets/4ab062e6-230a-4dba-82e9-8e0c1ad74806)
