### ISSUE TITLE
Logs: script no uploaded & directory structure

### ISSUE THREAD

**Issue by katilp** [cms-dpoa/cloud-processing#25]
If we upload the logs to this repository, it would be better to have them in a  `logs` subdirectory at the repository top level and then the separate log directories under it.

Also, one of the logs shows the output of a script that is not uploaded.

**Comment by katilp** [comment]
Also, we need to reflect on whether we want to have the logs in the repository or rather documented in the repository wiki.

If they are in the repository, they will be cloned to the local working area.

**Comment by subash-taranga** [comment]
I added logs in separate directory
